# Generated by Django 4.0.9 on 2023-02-15 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_members'),
        ('tree', '0002_alter_plantedtree_account_alter_plantedtree_tree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantedtree',
            name='account',
        ),
        migrations.AddField(
            model_name='plantedtree',
            name='account',
            field=models.ManyToManyField(blank=True, related_name='account_trees', to='account.account'),
        ),
    ]
