# Generated by Django 4.0.9 on 2023-02-14 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_alter_account_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
