# Generated by Django 4.0.9 on 2023-02-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_about',
            field=models.TextField(default='Awesome user!', null=True),
        ),
    ]
